# Generated by Django 2.1.2 on 2019-01-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plateno', models.CharField(db_column='plateNo', max_length=10)),
                ('wbno', models.CharField(db_column='WBNo', max_length=10)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('driver', models.CharField(max_length=30)),
                ('helper', models.CharField(max_length=30)),
                ('customer', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('trucktype', models.CharField(db_column='truckType', max_length=20)),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'table1',
                'managed': False,
            },
        ),
    ]
